name: Deploy to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - run: yarn install

    - run: yarn build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dothemath-app-web'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5a0c16ca3a50416d8e13463c63de64ef }}
        package: './build'
